<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9OTVNOD" failures="1" tests="1" name="TestTwo" time="39.331" errors="0" timestamp="16 Apr 2022 16:25:33 GMT">
  <testcase classname="testScritptTwo.StandardUser" name="standaredUser" time="9.103">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
	at testScritptTwo.StandardUser.standaredUser(StandardUser.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- standaredUser -->
</testsuite> <!-- TestTwo -->
